// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: protoc/ItemMinDto.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.wumadevs";

export interface ItemMinDto {
  id: number;
  icon: string;
  mainTypeId: number;
  name: string;
  qualityId: number;
  showTypes: string[];
}

export interface ItemListDto {
  list: ItemMinDto[];
}

function createBaseItemMinDto(): ItemMinDto {
  return { id: 0, icon: "", mainTypeId: 0, name: "", qualityId: 0, showTypes: [] };
}

export const ItemMinDto: MessageFns<ItemMinDto> = {
  encode(message: ItemMinDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.icon !== "") {
      writer.uint32(18).string(message.icon);
    }
    if (message.mainTypeId !== 0) {
      writer.uint32(24).int32(message.mainTypeId);
    }
    if (message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.qualityId !== 0) {
      writer.uint32(40).int32(message.qualityId);
    }
    for (const v of message.showTypes) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemMinDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemMinDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mainTypeId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.qualityId = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.showTypes.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemMinDto {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      icon: isSet(object.icon) ? globalThis.String(object.icon) : "",
      mainTypeId: isSet(object.mainTypeId) ? globalThis.Number(object.mainTypeId) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      qualityId: isSet(object.qualityId) ? globalThis.Number(object.qualityId) : 0,
      showTypes: globalThis.Array.isArray(object?.showTypes)
        ? object.showTypes.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ItemMinDto): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.icon !== "") {
      obj.icon = message.icon;
    }
    if (message.mainTypeId !== 0) {
      obj.mainTypeId = Math.round(message.mainTypeId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.qualityId !== 0) {
      obj.qualityId = Math.round(message.qualityId);
    }
    if (message.showTypes?.length) {
      obj.showTypes = message.showTypes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemMinDto>, I>>(base?: I): ItemMinDto {
    return ItemMinDto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemMinDto>, I>>(object: I): ItemMinDto {
    const message = createBaseItemMinDto();
    message.id = object.id ?? 0;
    message.icon = object.icon ?? "";
    message.mainTypeId = object.mainTypeId ?? 0;
    message.name = object.name ?? "";
    message.qualityId = object.qualityId ?? 0;
    message.showTypes = object.showTypes?.map((e) => e) || [];
    return message;
  },
};

function createBaseItemListDto(): ItemListDto {
  return { list: [] };
}

export const ItemListDto: MessageFns<ItemListDto> = {
  encode(message: ItemListDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.list) {
      ItemMinDto.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemListDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemListDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list.push(ItemMinDto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemListDto {
    return { list: globalThis.Array.isArray(object?.list) ? object.list.map((e: any) => ItemMinDto.fromJSON(e)) : [] };
  },

  toJSON(message: ItemListDto): unknown {
    const obj: any = {};
    if (message.list?.length) {
      obj.list = message.list.map((e) => ItemMinDto.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemListDto>, I>>(base?: I): ItemListDto {
    return ItemListDto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemListDto>, I>>(object: I): ItemListDto {
    const message = createBaseItemListDto();
    message.list = object.list?.map((e) => ItemMinDto.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
