// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: protoc/ItemDto.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.wumadevs";

export interface ItemDto {
  attributesDescription: string;
  bgDescription: string;
  destructible: boolean;
  icon: string;
  id: number;
  isBuffItem: boolean;
  itemAccess: string[];
  itemBuffType: number;
  itemType: number;
  mainTypeId: number;
  maxCapcity: number;
  maxStackableNum: number;
  name: string;
  numLimit: number;
  qualityId: number;
  showInBag: boolean;
  showTypes: string[];
  sortIndex: number;
  specialItem: boolean;
  uiPlayItem: boolean;
  useCountLimit: number;
  useLevel: number;
}

function createBaseItemDto(): ItemDto {
  return {
    attributesDescription: "",
    bgDescription: "",
    destructible: false,
    icon: "",
    id: 0,
    isBuffItem: false,
    itemAccess: [],
    itemBuffType: 0,
    itemType: 0,
    mainTypeId: 0,
    maxCapcity: 0,
    maxStackableNum: 0,
    name: "",
    numLimit: 0,
    qualityId: 0,
    showInBag: false,
    showTypes: [],
    sortIndex: 0,
    specialItem: false,
    uiPlayItem: false,
    useCountLimit: 0,
    useLevel: 0,
  };
}

export const ItemDto: MessageFns<ItemDto> = {
  encode(message: ItemDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attributesDescription !== "") {
      writer.uint32(10).string(message.attributesDescription);
    }
    if (message.bgDescription !== "") {
      writer.uint32(18).string(message.bgDescription);
    }
    if (message.destructible !== false) {
      writer.uint32(24).bool(message.destructible);
    }
    if (message.icon !== "") {
      writer.uint32(34).string(message.icon);
    }
    if (message.id !== 0) {
      writer.uint32(40).int32(message.id);
    }
    if (message.isBuffItem !== false) {
      writer.uint32(48).bool(message.isBuffItem);
    }
    for (const v of message.itemAccess) {
      writer.uint32(58).string(v!);
    }
    if (message.itemBuffType !== 0) {
      writer.uint32(64).int32(message.itemBuffType);
    }
    if (message.itemType !== 0) {
      writer.uint32(72).int32(message.itemType);
    }
    if (message.mainTypeId !== 0) {
      writer.uint32(80).int32(message.mainTypeId);
    }
    if (message.maxCapcity !== 0) {
      writer.uint32(88).int32(message.maxCapcity);
    }
    if (message.maxStackableNum !== 0) {
      writer.uint32(96).int32(message.maxStackableNum);
    }
    if (message.name !== "") {
      writer.uint32(106).string(message.name);
    }
    if (message.numLimit !== 0) {
      writer.uint32(112).int32(message.numLimit);
    }
    if (message.qualityId !== 0) {
      writer.uint32(120).int32(message.qualityId);
    }
    if (message.showInBag !== false) {
      writer.uint32(128).bool(message.showInBag);
    }
    for (const v of message.showTypes) {
      writer.uint32(138).string(v!);
    }
    if (message.sortIndex !== 0) {
      writer.uint32(144).int32(message.sortIndex);
    }
    if (message.specialItem !== false) {
      writer.uint32(152).bool(message.specialItem);
    }
    if (message.uiPlayItem !== false) {
      writer.uint32(160).bool(message.uiPlayItem);
    }
    if (message.useCountLimit !== 0) {
      writer.uint32(168).int32(message.useCountLimit);
    }
    if (message.useLevel !== 0) {
      writer.uint32(176).int32(message.useLevel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attributesDescription = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bgDescription = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.destructible = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isBuffItem = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.itemAccess.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.itemBuffType = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.itemType = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.mainTypeId = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.maxCapcity = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.maxStackableNum = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.numLimit = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.qualityId = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.showInBag = reader.bool();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.showTypes.push(reader.string());
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.sortIndex = reader.int32();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.specialItem = reader.bool();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.uiPlayItem = reader.bool();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.useCountLimit = reader.int32();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.useLevel = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemDto {
    return {
      attributesDescription: isSet(object.attributesDescription) ? globalThis.String(object.attributesDescription) : "",
      bgDescription: isSet(object.bgDescription) ? globalThis.String(object.bgDescription) : "",
      destructible: isSet(object.destructible) ? globalThis.Boolean(object.destructible) : false,
      icon: isSet(object.icon) ? globalThis.String(object.icon) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      isBuffItem: isSet(object.isBuffItem) ? globalThis.Boolean(object.isBuffItem) : false,
      itemAccess: globalThis.Array.isArray(object?.itemAccess)
        ? object.itemAccess.map((e: any) => globalThis.String(e))
        : [],
      itemBuffType: isSet(object.itemBuffType) ? globalThis.Number(object.itemBuffType) : 0,
      itemType: isSet(object.itemType) ? globalThis.Number(object.itemType) : 0,
      mainTypeId: isSet(object.mainTypeId) ? globalThis.Number(object.mainTypeId) : 0,
      maxCapcity: isSet(object.maxCapcity) ? globalThis.Number(object.maxCapcity) : 0,
      maxStackableNum: isSet(object.maxStackableNum) ? globalThis.Number(object.maxStackableNum) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      numLimit: isSet(object.numLimit) ? globalThis.Number(object.numLimit) : 0,
      qualityId: isSet(object.qualityId) ? globalThis.Number(object.qualityId) : 0,
      showInBag: isSet(object.showInBag) ? globalThis.Boolean(object.showInBag) : false,
      showTypes: globalThis.Array.isArray(object?.showTypes)
        ? object.showTypes.map((e: any) => globalThis.String(e))
        : [],
      sortIndex: isSet(object.sortIndex) ? globalThis.Number(object.sortIndex) : 0,
      specialItem: isSet(object.specialItem) ? globalThis.Boolean(object.specialItem) : false,
      uiPlayItem: isSet(object.uiPlayItem) ? globalThis.Boolean(object.uiPlayItem) : false,
      useCountLimit: isSet(object.useCountLimit) ? globalThis.Number(object.useCountLimit) : 0,
      useLevel: isSet(object.useLevel) ? globalThis.Number(object.useLevel) : 0,
    };
  },

  toJSON(message: ItemDto): unknown {
    const obj: any = {};
    if (message.attributesDescription !== "") {
      obj.attributesDescription = message.attributesDescription;
    }
    if (message.bgDescription !== "") {
      obj.bgDescription = message.bgDescription;
    }
    if (message.destructible !== false) {
      obj.destructible = message.destructible;
    }
    if (message.icon !== "") {
      obj.icon = message.icon;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.isBuffItem !== false) {
      obj.isBuffItem = message.isBuffItem;
    }
    if (message.itemAccess?.length) {
      obj.itemAccess = message.itemAccess;
    }
    if (message.itemBuffType !== 0) {
      obj.itemBuffType = Math.round(message.itemBuffType);
    }
    if (message.itemType !== 0) {
      obj.itemType = Math.round(message.itemType);
    }
    if (message.mainTypeId !== 0) {
      obj.mainTypeId = Math.round(message.mainTypeId);
    }
    if (message.maxCapcity !== 0) {
      obj.maxCapcity = Math.round(message.maxCapcity);
    }
    if (message.maxStackableNum !== 0) {
      obj.maxStackableNum = Math.round(message.maxStackableNum);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.numLimit !== 0) {
      obj.numLimit = Math.round(message.numLimit);
    }
    if (message.qualityId !== 0) {
      obj.qualityId = Math.round(message.qualityId);
    }
    if (message.showInBag !== false) {
      obj.showInBag = message.showInBag;
    }
    if (message.showTypes?.length) {
      obj.showTypes = message.showTypes;
    }
    if (message.sortIndex !== 0) {
      obj.sortIndex = Math.round(message.sortIndex);
    }
    if (message.specialItem !== false) {
      obj.specialItem = message.specialItem;
    }
    if (message.uiPlayItem !== false) {
      obj.uiPlayItem = message.uiPlayItem;
    }
    if (message.useCountLimit !== 0) {
      obj.useCountLimit = Math.round(message.useCountLimit);
    }
    if (message.useLevel !== 0) {
      obj.useLevel = Math.round(message.useLevel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemDto>, I>>(base?: I): ItemDto {
    return ItemDto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemDto>, I>>(object: I): ItemDto {
    const message = createBaseItemDto();
    message.attributesDescription = object.attributesDescription ?? "";
    message.bgDescription = object.bgDescription ?? "";
    message.destructible = object.destructible ?? false;
    message.icon = object.icon ?? "";
    message.id = object.id ?? 0;
    message.isBuffItem = object.isBuffItem ?? false;
    message.itemAccess = object.itemAccess?.map((e) => e) || [];
    message.itemBuffType = object.itemBuffType ?? 0;
    message.itemType = object.itemType ?? 0;
    message.mainTypeId = object.mainTypeId ?? 0;
    message.maxCapcity = object.maxCapcity ?? 0;
    message.maxStackableNum = object.maxStackableNum ?? 0;
    message.name = object.name ?? "";
    message.numLimit = object.numLimit ?? 0;
    message.qualityId = object.qualityId ?? 0;
    message.showInBag = object.showInBag ?? false;
    message.showTypes = object.showTypes?.map((e) => e) || [];
    message.sortIndex = object.sortIndex ?? 0;
    message.specialItem = object.specialItem ?? false;
    message.uiPlayItem = object.uiPlayItem ?? false;
    message.useCountLimit = object.useCountLimit ?? 0;
    message.useLevel = object.useLevel ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
